### ISSUE TITLE
livedb-mongo 0.2.x loads livedb 0.3.0 via dependency

### ISSUE THREAD

**Issue by menssen** [share/livedb-mongo#4]
The dependency on livedb prior to the 0.3.0 release was ">0.2.7". That means that a dependency on livedb-mongo 0.2.* will install livdb 0.3.0 (since it's greater than 0.2.7), which is incompatible with the last 0.2.x livedb-mongo.

Seems like a solution would be another 0.2.x release of livedb-mongo that depended on livedb <0.3.0.

I realize this won't be a problem for long, but it is currently breaking the Derby.js new project generator, which specifies livedb-mongo 0.2.x, which is in turn installing livedb 0.3.0.

**Comment by nateps** [comment]
livedb is just a dev dependency now.
